# ----------------------- #
#      Main Configs       #
# ----------------------- #
url: http://www.jtianling.com
title: 九天雁翎的博客
name: 九天雁翎的博客
subtitle: 程序即人生
author: 九天雁翎
simple_search: https://www.google.com/search
description: 九天雁翎的博客(原程序即人生), 主要是记录自己学习编程的过程, 不过各种爱好都可能会写一些, 比如玩过的游戏, 看过的电影, 读过的书, 走过的路.
tagline: 如果你想在软件业获得成功，就使用你知道的最强大的语言，用它解决你知道的最难的问题，并且等待竞争对手的经理做出自甘平庸的选择。 -- Paul Graham

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /feed.xml

root: /
date_format: "%Y-%m-%d"
# github need
safe: false
lsi: false
source: .
destination: ./_site
layouts_dir:     ./_layouts
include:     ['.htaccess']
exclude:     ['Gemfile', 'Gemfile.lock', 'README.md', '/vendor']
keep_files:  ['.git','.svn']
plugins: [jekyll-paginate]
timezone:    Asia/Shanghai
encoding:    utf-8

future:      true
show_drafts: nil
limit_posts: 0
syntax_highlighter: rouge

permalink:     /:title.html
paginate_path: 'page:num'
paginate:      10

markdown_ext:  md
kramdown:
  input: GFM

excerpt_separator: "<!-- more -->"

host:        127.0.0.1
port:        8080
baseurl:     /
